packages:
  branch_codenames:
    master: unstable
    production: stable

github_base_url: "https://github.com/madebymany/redis-package"

jobs:
  redis:
    builder: "make"
    base: "quay.io/madebymany/build-bases:trusty"
    promote_through:
      - unstable
      - stable
    packages:
      - type: debian
        name: redis
        version: 2.8.3
        repos:
          - mxm-public
        target: install
      - type: debian
        name: redis-runit
        depends:
          - "runit-common"
          - "slackcat"
          - "redis"
        version: 0.0.1
        repos:
          - mxm-public
        target: install-runit
